### ISSUE TITLE
Interop for Multimedia Timer

### ISSUE THREAD

**Issue by Noemata** [robmikh/WinRTInteropTools#2]
Is there some way to create an interop for Multimedia Timer services?

As in what you would do under Win32:

```
    [DllImport("winmm.dll", SetLastError = true, EntryPoint = "timeSetEvent")]
    internal static extern UInt32 TimeSetEvent(UInt32 msDelay, UInt32 msResolution, MultimediaTimerCallback callback, ref UInt32 userCtx, UInt32 eventType);

    [DllImport("winmm.dll", SetLastError = true, EntryPoint = "timeKillEvent")]
    internal static extern void TimeKillEvent(UInt32 uTimerId);
```

If not, is there some alternative to high resolution timers under UWP, or a way to create a Win32 service that could fire such events into a UWP process?

This is a glaring whole in UWP.  I have not been able to resolve any alternative that does not involve pinning a CPU thread for that purpose.  If we must go the CPU thread approach, is there a prescribed best practice for using that approach?

**Comment by robmikh** [comment]
I would look into using something like the [`ThreadPoolTimer`](https://docs.microsoft.com/en-us/uwp/api/Windows.System.Threading.ThreadPoolTimer?view=winrt-19041) or a [`DispatcherQueueTimer`](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueuetimer?view=winrt-19041) on a dedicated thread.

**Comment by Noemata** [comment]
Neither ThreadPoolTimer or DispatcherQueueTimer are anywhere close to good enough for things like MIDI timers (just one example).  I would not have asked the question so naively.  Presently I'm using a thread that locks up one CPU core.  It works, but needlessly uses up a CPU core and also has nasty battery usage ramifications.  I've been tempted to post the solution to nudge things  along toward a better solution but am worried others will start to use it to excess, thus creating a negative impression of UWP.

**Comment by robmikh** [comment]
Well, that's all I've got. Good luck!
