### ISSUE TITLE
 how to use CaptureItemInterop.CreateForWindow? 

### ISSUE THREAD

**Issue by parker-wang** [robmikh/WinRTInteropTools#3]
I want to use CaptureItemInterop.CreateForWindow to get GraphicsCaptureItem via Hwnd in UWP.
The code is as follows:
      var item =  CaptureItemInterop.CreateForWindow(Convert.ToUInt64("000811BA", 16));
            if (item == null)
            {
                Debug.WriteLine("capture success");
            }
 
but an error occurred :
 Debugging resource strings are unavailable System.Runtime.InteropServices.COMException: No registration class.
Can you tell me how to fix it？

**Comment by robmikh** [comment]
The `CreateForWindow` and `CreateForMonitor` APIs are not available to UWP and LowIL callers. 

In Windows 11, a UWP friendly version of the API was released. See [this issue](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/101#issuecomment-1029830711) for more details.
